package com.example.data.repository

import com.example.data.api.Content
import com.example.data.api.GeminiRequest
import com.example.data.api.GeminiStoryResponse
import com.example.data.api.GenerationConfig
import com.example.data.api.Part
import com.example.data.api.RetrofitClient
import com.example.data.local.StoryDao
import com.example.data.local.StoryEntity
import com.example.data.api.QuizQuestion
import com.squareup.moshi.Types
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext

class StoryRepository(private val storyDao: StoryDao) {

    val allStories: Flow<List<StoryEntity>> = storyDao.getAllStories()

    suspend fun getStoryById(id: Int): StoryEntity? {
        return storyDao.getStoryById(id)
    }

    suspend fun deleteStoryById(id: Int) {
        storyDao.deleteStoryById(id)
    }

    suspend fun generateAndSaveStory(
        heroName: String,
        heroType: String,
        theme: String,
        setting: String,
        tone: String,
        language: String
    ): StoryEntity = withContext(Dispatchers.IO) {
        val displayLanguage = if (language == "ar") "Arabic (العربية)" else "English"
        
        val prompt = """
            You are a professional children's book author with 20 years of experience writing highly engaging, creative, and educational stories that are interactive, fun, and morally upright.
            Please write a children's story in $displayLanguage.
            
            Story Settings:
            - Protagonist/Hero Name: $heroName
            - Protagonist/Hero Character Type: $heroType
            - Backstage Setting or Place: $setting
            - Educational Goal and Theme: $theme
            - Story Tone and Style: $tone
            
            Let the story be extremely fascinating and magical. If generating in Arabic, it MUST contain simple elegant phrasing with appropriate partial vocalization (تَشْكِيل بَسِيط) to help children read and learn. Make the events exciting with clear, relatable actions.
            
            You MUST return a JSON object with this exact structure:
            {
              "title": "The beautiful creative story title",
              "storyContent": "The full complete storytelling narrative. Expand it in 3 to 4 paragraphs, with great flow and immersive vocabulary.",
              "moral": "A short, beautiful, and simplified moral/educational explanation of the theme, directed warmly to the child.",
              "quiz": [
                {
                  "question": "A comprehension question about what happened in the story.",
                  "options": ["Option 1", "Option 2", "Option 3"],
                  "correctOptionIndex": 0
                },
                {
                  "question": "A question testing if they understood the moral theme are why the hero made a certain decision.",
                  "options": ["Option 1", "Option 2", "Option 3"],
                  "correctOptionIndex": 1
                },
                {
                  "question": "An extremely fun secondary trivia question based on any interesting detail in the story.",
                  "options": ["Option 1", "Option 2", "Option 3"],
                  "correctOptionIndex": 2
                }
              ]
            }
            
            Ensure the quiz contains exactly 3 multiple choice questions, and the correctOptionIndex corresponds to the correct option string's list index (0, 1, or 2).
            Output ONLY the raw content-type JSON object. Absolutely no surrounding markdown block, no ```json tags, and no leading/trailing prose.
        """.trimIndent()

        val systemInstruction = "You are a master writer of children's stories. You only output valid JSON conforming to the requested schema, never anything else."

        val request = GeminiRequest(
            contents = listOf(
                Content(parts = listOf(Part(text = prompt)))
            ),
            generationConfig = GenerationConfig(
                responseMimeType = "application/json",
                temperature = 0.8
            ),
            systemInstruction = Content(parts = listOf(Part(text = systemInstruction)))
        )

        // Remote fetch from Gemini api
        val result = RetrofitClient.service.generateContent(request = request)
        val responseText = result.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
            ?: throw Exception("No story generated by the intelligence model. Please try again.")

        // Parse using Moshi to secure types
        val adapter = RetrofitClient.moshiParser.adapter(GeminiStoryResponse::class.java)
        val storyResponse = adapter.fromJson(responseText)
            ?: throw Exception("Failed to serialize story format. Raw output was: $responseText")

        val quizType = Types.newParameterizedType(List::class.java, QuizQuestion::class.java)
        val quizJsonString = RetrofitClient.moshiParser.adapter<List<QuizQuestion>>(quizType).toJson(storyResponse.quiz)

        // Save into Room database
        val entity = StoryEntity(
            title = storyResponse.title,
            heroName = heroName,
            heroType = heroType,
            theme = theme,
            setting = setting,
            tone = tone,
            storyContent = storyResponse.storyContent,
            moral = storyResponse.moral,
            quizJson = quizJsonString,
            language = language
        )

        val insertedId = storyDao.insertStory(entity)
        entity.copy(id = insertedId.toInt())
    }
}
